const cities = [
    'Antalya',
    'Bangkok',
    'Barcelona',
    'Bali',
    'Berlin',
    'Boston',
    'Bordeaux',
    'Chicago',
    'Dublin',
    'Dubai',
    'Hong Kong',
    'Istanbul',
    'Kuala Lumpur',
    'Kyoto',
    'Lima',
    'London',
    'Marseille',
    'Madrid',
    'Montreal',
    'Mexico',
    'Mexico City',
    'Milan',
    'Moscow',
    'New York',
    'Osaka',
    'Paris',
    'Phuket',
    'Prague',
    'Rome',
    'San Francisco',
    'Santa Cruz',
    'Seoul',
    'Singapore',
    'Shangai',
    'Stockholm',
    'Torino',
    'Tokyo',
];

export function cityIsFamous(city: string) {
    return cities.includes(city);
}

