const cities = [
    'Accra',
    'Antalya',
    'Antananarivo',
    'Ankara',
    'Amsterdam',
    'Antigua',
    'Anchorage',
    'Aswan',
    'Ashgabat',
    'Athens',
    'Atlanta',
    'Auckland',
    'Bangkok',
    'Bamako',
    'Barcelona',
    'Bali',
    'Bath',
    'Beijing',
    'Belgrade',
    'Belfast',
    'Berlin',
    'Bern',
    'Bled',
    'Bogota',
    'Bologna',
    'Boston',
    'Bordeaux',
    'Bratislava',
    'Brussels',
    'Bucharest',
    'Budapest',
    'Bukhara',
    'Cairo',
    'Canberra',
    'Cancun',
    'Cannes',
    'Cape Town',
    'Caracas',
    'Carcassonne',
    'Cartagena',
    'Casablanca',
    'Chengdu',
    'Chicago',
    'Chiang Mai',
    'Christchurch',
    'Cologne',
    'Colombo',
    'Copenhagen',
    'Cusco',
    'Dakar',
    'Dar Es Salaam',
    'Detroit',
    'Doha',
    'Dresden',
    'Dublin',
    'Dubai',
    'Dubrovnik',
    'Edinburgh',
    'Fes',
    'Hanoi',
    'Hangzhou',
    'Harare',
    'Havana',
    'Hamburg',
    'Heidelberg',
    'Helsinki',
    'Hobart',
    'Ho Chi Minh City',
    'Geneva',
    'Genoa',
    'Granada',
    'Glasgow',
    'Guangzhou',
    'Frankfurt',
    'Fukuoka',
    'Hiroshima',
    'Hong Kong',
    'Izmir',
    'Istanbul',
    'Jaipur',
    'Jerusalem',
    'Jericho',
    'Johannesburg',
    'Kathmandu',
    'Kiev',
    'Kingston',
    'Kuala Lumpur',
    'Krakow',
    'Kolkata',
    'Kyoto',
    'Lagos',
    'La Paz',
    'Las Vegas',
    'Lalibella',
    'Lausanne',
    'Lhasa',
    'Lima',
    'Lisbon',
    'Liverpool',
    'Ljubljana',
    'London',
    'Los Angeles',
    'Luang Prabang',
    'Lubeck',
    'Lyon',
    'Macau',
    'Madrid',
    'Male',
    'Malmo',
    'Manaus',
    'Manchester',
    'Manila',
    'Managua',
    'Marrakech',
    'Marseille',
    'Melbourne',
    'Mexico',
    'Mexico City',
    'Minsk',
    'Milan',
    'Miami',
    'Montreal',
    'Montevideo',
    'Moscow',
    'Munich',
    'Mumbai',
    'Monaco',
    'Nassau',
    'Naples',
    'Nairobi',
    'Nagoya',
    'New York',
    'New Orleans',
    'New Delhi',
    'Nuremberg',
    'Orlando',
    'Osaka',
    'Oslo',
    'Ottawa',
    'Paris',
    'Panama',
    'Panama City',
    'Petra',
    'Phnom Penh',
    'Phuket',
    'Philadelphia',
    'Pretoria',
    'Porto',
    'Prague',
    'Quebec',
    'Quito',
    'Reykjavik',
    'Recife',
    'Rio',
    'Rio de Janeiro',
    'Riga',
    'Riyadh',
    'Rome',
    'Rotterdam',
    'Salvador',
    'Salt Lake City',
    'Sao Paulo',
    'San Francisco',
    'San Jose',
    'San Juan',
    'Santa Cruz',
    'Sarajevo',
    'Santiago',
    'Siena',
    'Siem Reap',
    'Seattle',
    'Seoul',
    'Seville',
    'Sevilla',
    'Sofia',
    'Shanghai',
    'Shenzhen',
    'Singapore',
    'Strasbourg',
    'Sydney',
    'St. Louis',
    'St. Petersburg',
    'Stockholm',
    'Suva',
    'Taipei',
    'Tallinn',
    'Tbilisi',
    'Tel Aviv',
    'Turin',
    'Torino',
    'Toronto',
    'Tokyo',
    'Toulouse',
    'Ulan Bator',
    'Ushuaia',
    'Varanasi',
    'Valparaiso',
    'Varna',
    'Venice',
    'Vienna',
    'Vilnius',
    'Vientiane',
    'Warsaw',
    'Washington',
    'Wellington',
    'Windhoek',
    'Yerevan',
    'Yangon',
    'Zanzibar',
    'Zurich',
];

export function cityIsFamous(city: string) {
    return cities.includes(city);
}

